### ISSUE TITLE
Blocks the usage of the Matrix field when added in a Global set.

### ISSUE THREAD

**Issue by bzin** [monachilada/craft-matrixtoolbar#2]
When the plugin is installed and enabled. The Matrix fields that are in a Global Set do not work since you have a javascript error. 

<img width="1106" alt="screen shot 2018-10-08 at 18 33 44" src="https://user-images.githubusercontent.com/382735/46621783-b6c08200-cb28-11e8-97ea-937328d50c37.png">

**Comment by monachilada** [comment]
Thanks for pointing that out. The error shouldn't occur any more, but I'm realising that unfortunately there's no quick way of enabling the toolbar for Matrix fields in global sets without refactoring my code significantly. I've added it as a TODO for a future release.

**Comment by monachilada** [comment]
This is enabled in the new version 1.0.6. But Craft 3.0.27 or above is required.
